
FROM maven:3.9.6-eclipse-temurin-17 AS builder
WORKDIR /app

COPY pom.xml .
RUN mvn dependency:go-offline -B

COPY src ./src

RUN mvn package -DskipTests
FROM gcr.io/distroless/java17-debian12
COPY --from=builder /app/target/*.jar app.jar

CMD ["app/app.jar"]
